# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cumulative_matrix <- function(X, pathway_sizes, reference_scores, sampling_size, display_progress = TRUE) {
    .Call('_pwannot_cumulative_matrix', PACKAGE = 'pwannot', X, pathway_sizes, reference_scores, sampling_size, display_progress)
}

reference_matrix <- function(X, ind) {
    .Call('_pwannot_reference_matrix', PACKAGE = 'pwannot', X, ind)
}

