# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cumulative_matrix <- function(X, pathway_sizes, reference_scores, sampling_size = 100L) {
    .Call(`_pwannot_cumulative_matrix`, X, pathway_sizes, reference_scores, sampling_size)
}

rcpparma_hello_world <- function() {
    .Call(`_pwannot_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_pwannot_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_pwannot_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_pwannot_rcpparma_bothproducts`, x)
}

reference_matrix <- function(X, ind) {
    .Call(`_pwannot_reference_matrix`, X, ind)
}

